 # Spring profiles
spring.profiles.default=local

# JPA settings
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

# SpringDoc OpenAPI settings
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.with-credentials=true
springdoc.swagger-ui.persist-authorization=true
